# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - develop
  
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  GitVersion.SemVer: ''

steps:

- task: gitversion/setup@0
  displayName: Setup GitVersion Tool
  inputs:
    versionSpec: '5.6.0'
    includePrerelease: true

- task: gitversion/execute@0
  displayName: Run GitVersion
  inputs:
    useConfigFile: true
    configFilePath: "./GitVersion.yml"

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- script: dotnet build --configuration $(buildConfiguration) /p:AssemblyVerison='$(GitVersion.SemVer)'
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test
  displayName: 'dotnet test'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: './src/Extensions.Pack/Extensions.Pack.csproj'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'