<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageLicenseFile>License.txt</PackageLicenseFile>
        <Authors>Rene Peuser</Authors>
        <Company>Rene Peuser Softwaresolutions</Company>
        <Description>A set of useful extensions to make your code smooth and nice readable.</Description>
        <Copyright>Copyright 2020 (c) Rene Peuser. All rights reserved.</Copyright>
        <PackageProjectUrl>https://renepeuser.visualstudio.com/Extensions.Pack</PackageProjectUrl>
        <RepositoryUrl>https://renepeuser.visualstudio.com/Extensions.Pack</RepositoryUrl>
        <PackageReleaseNotes>
           - Package upgrade to .Net 9
        </PackageReleaseNotes>
        <PackageTags>C#;.Net;Net5;extension;extensions;extend;static;this;static;System;System.Collections.Generic;System.Globalization;System.IO;System.Linq;System.Reflection;System.Xml;Pack;</PackageTags>
        <PackageId>Extensions.Pack</PackageId>
        <OutputType>Library</OutputType>
        <LangVersion>latest</LangVersion>
        <NoWarn>CA1054;CA2234;CA1002;CA1055</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DocumentationFile>..\..\Extensions.Pack.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DocumentationFile>..\..\Extensions.Pack.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\License.txt">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Argument.Check" Version="5.0.5" />
        <PackageReference Include="ConsoleTables" Version="2.6.2" />
        <PackageReference Include="GitVersion.MsBuild" Version="5.12.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.4" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.4" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.4" />
    </ItemGroup>

</Project>
