<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
		<PackageLicenseFile>License.txt</PackageLicenseFile>
		<Authors>Rene Peuser</Authors>
		<Company>Rene Peuser Softwaresolutions</Company>
		<Description>A set of useful extensions to make your code smooth and nice readable.</Description>
		<Copyright>Copyright 2020 (c) Rene Peuser. All rights reserved.</Copyright>
		<PackageProjectUrl>https://renepeuser.visualstudio.com/Extensions.Pack</PackageProjectUrl>
		<RepositoryUrl>https://renepeuser.visualstudio.com/Extensions.Pack</RepositoryUrl>
        <PackageReleaseNotes>
A set of extensions for following namespaces:

System
System.Collections.Generic
System.Globalization
System.IO
System.Linq
System.Reflection
System.Xml

Package was upgarded to Net5.0, if you want to use it in lower version take an earlier version.
		</PackageReleaseNotes>
		<PackageTags>C#;.Net;Net5;extension;extensions;extend;static;this;static;System;System.Collections.Generic;System.Globalization;System.IO;System.Linq;System.Reflection;System.Xml;Pack;</PackageTags>
		<PackageId>Extensions.Pack</PackageId>
		<OutputType>Library</OutputType>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <DocumentationFile>..\..\Extensions.Pack.xml</DocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DocumentationFile>..\..\Extensions.Pack.xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\License.txt">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="GitVersion.MsBuild" Version="5.6.6">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

</Project>
